USE [master]
GO

/****** Object:  Database [CodeChallenge]    Script Date: 3/29/2022 9:44:54 PM ******/
CREATE DATABASE [CodeChallenge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CodeChallenge', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CodeChallenge.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CodeChallenge_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CodeChallenge_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CodeChallenge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CodeChallenge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CodeChallenge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CodeChallenge] SET ARITHABORT OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CodeChallenge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CodeChallenge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CodeChallenge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CodeChallenge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CodeChallenge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CodeChallenge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CodeChallenge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CodeChallenge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CodeChallenge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CodeChallenge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CodeChallenge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CodeChallenge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CodeChallenge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CodeChallenge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CodeChallenge] SET RECOVERY FULL 
GO

ALTER DATABASE [CodeChallenge] SET  MULTI_USER 
GO

ALTER DATABASE [CodeChallenge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CodeChallenge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CodeChallenge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CodeChallenge] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CodeChallenge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CodeChallenge] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CodeChallenge] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CodeChallenge] SET  READ_WRITE 
GO

